// Copyright 2026 The MathWorks, Inc.
//
// Defect 25: a char array's SHAPE, in every channel a char travels through.
//
// Every char in the parity corpus was a row vector (charStr 1x4, longChar 1x300,
// hugeChar 1x1500), so no channel had ever been asked the shape question for this
// class. `test/parity/matlab/probe_char_shape.m` asked it — a 2x2, a 2x3, a 3x1
// column, an empty, a 2x3x2 and a numeric control, written to both dictionary
// flavours — and MATLAB turned out to have TWO spellings, neither of them ours:
//
//   text .sldd    a 1xN row is a bare JSON string ("it's"); anything else is
//                 {"_type":"mxchar","_value":"Matrix(2,2)\n[[97, 98]; [99, 100]]"} —
//                 character CODES, one bracketed group per ROW; rank >= 3 falls back
//                 to a cdata MAT stream, as every class does there (defect 22).
//   binary/.slx   <P Class="char" Dimension="2*2">acbd</P>, the text column-major;
//                 a 1xN row and an empty char carry NO Dimension at all.
//
// We read neither. The Dimension= was ignored at all three sites that consumed it and
// the mxchar envelope was unknown, so MATLAB's own 2x2 came back as a 1x1 char holding
// 'acbd' — the shape gone AND the characters in an order nobody had typed. On the way
// out a char field of a struct went through the generic typed-value path and became
// `Class="mxchar" Dimension="2*2">97 99 98 100`: a class MATLAB does not have, holding
// numbers where its characters were. And the table seeds a char matrix's editor with
// its own displayed literal, which the value parser read as a string array — so
// committing `['ab'; 'cd']` unchanged retyped the entry char -> string and reshaped it
// 2x2 -> 2x1.
//
// The fix is one invariant rather than four special cases: a char is ONE
// `_kind:'scalar'`, `_scalarType:'char'` node whose `_scalarValue` holds the whole
// text in MATLAB's own column-major storage order, with the real extents on `_dims`.
// That is already what a .mat char payload carries — MatParser deliberately does not
// transpose it, and MatWriter.charBody says so — and what the XML body carries, so
// the four channels differ only in how they SPELL a shape they now share. One rule
// decides that: charNeedsShape(dims), the char twin of defect 21's row-vector rule.
//
// Both fixtures below were written by MATLAB and are never regenerated by us, so every
// assertion here is against MATLAB's own bytes.
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { unzipSync } from 'fflate';
import { loadFile, findEntry } from './parity/loadFile.js';
import MatlabValueParser from '../src/datamodel/parser/MatlabValueParser.js';
import { charNeedsShape } from '../src/datamodel/parser/XmlUtils.js';
import '../src/datamodel/node/NodeClassMap.js';

// ---- MATLAB's bytes, both flavours -------------------------------------------

const TEXT_RAW: { name: string; value: unknown }[] = JSON.parse(
  readFileSync(fileURLToPath(new URL('./fixtures/char_text.sldd', import.meta.url)), 'utf8'),
).__MW_TEXT_PARTS__['__MW_TEXT_PART__/data/chunk0'].__MW_TEXT_content.entries;

function textTruth(name: string): unknown {
  const hit = TEXT_RAW.find((e) => e.name === name);
  expect(hit, name + ' is not in char_text.sldd').toBeTruthy();
  return (hit as { value: unknown }).value;
}

const BIN_XML = new TextDecoder().decode(
  unzipSync(
    new Uint8Array(readFileSync(fileURLToPath(new URL('./fixtures/char_binary.sldd', import.meta.url)))),
  )['data/chunk0.xml'],
);

/** The `<P Name="Value" …>` tag MATLAB wrote for one entry of the binary dictionary. */
function xmlTruth(name: string): string {
  for (const obj of BIN_XML.match(/<Object Class="DD\.ENTRY">[\s\S]*?<\/Object>/g) ?? []) {
    if (obj.indexOf('<P Name="Name" Class="char">' + name + '</P>') < 0) {
      continue;
    }
    const m = /<P Name="Value"[^>]*(?:\/>|>[\s\S]*?<\/P>)/.exec(obj);
    expect(m, name + ' has no Value property in char_binary.sldd').toBeTruthy();
    return (m as RegExpExecArray)[0];
  }
  throw new Error('no entry "' + name + '" in char_binary.sldd');
}

const FLAVOURS: Array<[string, string]> = [
  ['text', '../fixtures/char_text.sldd'],
  ['binary', '../fixtures/char_binary.sldd'],
];

/**
 * Mark this node AND every node under it modified, so the WRITER produces the value
 * instead of the reader replaying it. `_markModified` walks up and never down, so
 * without this a container is a byte copy of the fixture and the writer was never
 * asked anything — see the same helper in typedShapes.test.ts.
 */
function deepMark(n: any): void {
  n._markModified();
  for (const c of n.children ?? []) {
    deepMark(c);
  }
}

function entry(rel: string, name: string, mark?: boolean): any {
  const n = findEntry(loadFile(rel, rel.split('/').pop() as string), name);
  if (mark) {
    deepMark(n);
  }
  return n;
}

// name, MATLAB's size(), the display, the column-major storage text, editable
const CASES: Array<[string, number[], string, string, boolean]> = [
  ['charRow', [1, 4], "'it''s'", "it's", true],
  ['charEmpty', [0, 0], "''", '', true],
  ['charCol', [3, 1], "['a'; 'b'; 'c']", 'abc', true],
  ['charMat', [2, 2], "['ab'; 'cd']", 'acbd', true],
  ['charMat23', [2, 3], "['ace'; 'bdf']", 'abcdef', true],
  // Rank >= 3 has no MATLAB one-line print, of chars or of anything else. It used to
  // show as one quoted 12-character string, which is the storage and not the value.
  ['ndChar', [2, 3, 2], '<2x3x2 char>', 'abcdefghijkl', false],
];

describe('a char array reads as one node, at MATLAB’s shape, from either flavour', () => {
  it('covers every entry the fixture carries', () => {
    // A regenerated fixture that loses a shape must not quietly shrink the suite.
    expect(TEXT_RAW.map((e) => e.name).sort()).toEqual([
      'charCol', 'charEmpty', 'charMat', 'charMat23', 'charRow', 'ndChar', 'ndDouble',
    ]);
  });

  for (const [flavour, rel] of FLAVOURS) {
    for (const [name, dims, display, text, editable] of CASES) {
      it(`${flavour} ${name}: scalar char, dims ${dims.join('x')}, shows ${display}`, () => {
        const n = entry(rel, name);
        // One kind for every char, at every rank: the whole text in one scalar, with
        // the extents beside it. Not an 'array' of per-character children — a char is
        // one value, and MATLAB's Value column shows it as one.
        expect([n._kind, n._scalarType, n.dataType]).toEqual(['scalar', 'char', 'char']);
        expect(n._scalarValue).toBe(text);
        expect(n.dims).toEqual(dims);
        expect(n.children.length).toBe(0);
        expect(n.displayValue).toBe(display);
        // A summary is not a literal, so it cannot be typed back in.
        expect(n.valueEditable).toBe(editable);
      });
    }
  }

  it('the two flavours agree, entry for entry', () => {
    // The point of reading both: one spelling in JSON, another in XML, one node.
    const shapeOf = (rel: string) =>
      CASES.map(([name]) => {
        const n = entry(rel, name);
        return [n._kind, n._scalarType, n.dims, n._scalarValue, n.displayValue];
      });
    expect(shapeOf('../fixtures/char_text.sldd')).toEqual(shapeOf('../fixtures/char_binary.sldd'));
  });

  it('charEmpty is 0x0 — MATLAB’s own size for the empty char', () => {
    // numel 0 and isempty true. The bare-string channel leaves _dims at [1,1], which
    // would claim one character where there are none, so the shape is derived from the
    // text (_textDims) rather than believed.
    for (const [, rel] of FLAVOURS) {
      expect(entry(rel, 'charEmpty').dims).toEqual([0, 0]);
    }
  });
});

describe('a char array writes the bytes MATLAB wrote, in both channels', () => {
  for (const [flavour, rel] of FLAVOURS) {
    for (const [name] of CASES) {
      it(`${flavour} ${name}: the text .sldd value is byte-identical`, () => {
        expect(entry(rel, name, true).serializeValue()).toEqual(textTruth(name));
      });

      it(`${flavour} ${name}: the XML property is byte-identical`, () => {
        expect(entry(rel, name, true).serializeXml('P', { Name: 'Value' }, 0)).toBe(xmlTruth(name));
      });
    }
  }

  it('the mxchar body carries character CODES, one group per row', () => {
    // The spelling itself, stated once: a column is a flat body under a header, a
    // matrix is '; '-joined bracketed groups — never the newline-joined body MATLAB
    // reads back as an empty 1x0 (defect 19).
    expect(entry('../fixtures/char_text.sldd', 'charCol', true).serializeValue()).toEqual({
      _type: 'mxchar',
      _value: 'Matrix(3,1)\n[97, 98, 99]',
    });
    expect(entry('../fixtures/char_text.sldd', 'charMat', true).serializeValue()).toEqual({
      _type: 'mxchar',
      _value: 'Matrix(2,2)\n[[97, 98]; [99, 100]]',
    });
  });

  it('a row and an empty char state no shape at all', () => {
    // The char half of defect 21: a bare JSON string reads back AS a row, so saying
    // 1xN would be churn, and MATLAB says nothing there either.
    expect(entry('../fixtures/char_text.sldd', 'charRow', true).serializeValue()).toBe("it's");
    expect(entry('../fixtures/char_text.sldd', 'charEmpty', true).serializeValue()).toBe('');
    expect(entry('../fixtures/char_binary.sldd', 'charRow', true).serializeXml('P', { Name: 'Value' }, 0))
      .not.toContain('Dimension');
  });

  it('a rank-3 char falls back to a cdata MAT stream, not an mxchar', () => {
    // Defect 22's rule is class-independent: the bracketed literal is 2-D only, so at
    // rank 3 MATLAB embeds a MAT stream. `Matrix(2,3,2)` would be a body no MATLAB
    // reads.
    const v = entry('../fixtures/char_text.sldd', 'ndChar', true).serializeValue() as any;
    expect(v._type).toBe('cdata');
    expect(v).toEqual(textTruth('ndChar'));
  });

  it('never writes Class="mxchar" — MATLAB has no such class', () => {
    // The tag name is our JSON envelope, not a MATLAB class. Written through the
    // generic typed-value path it leaked into the XML channel as
    // `Class="mxchar" Dimension="2*2">97 99 98 100`.
    for (const [, rel] of FLAVOURS) {
      for (const [name] of CASES) {
        expect(entry(rel, name, true).serializeXml('P', { Name: 'Value' }, 0)).not.toContain('mxchar');
      }
    }
  });

  it('the .mat snapshot names every extent too', () => {
    // The fourth writer. `dimensions` feeds MatWriter, whose char body is the same
    // column-major text — so this channel needs no transpose, only the shape.
    for (const [name, dims, , text] of CASES) {
      const v = entry('../fixtures/char_text.sldd', name)._var;
      expect([v.className, v.dimensions, v.value], name).toEqual(['char', dims, text]);
    }
  });
});

describe('a char field or element keeps its shape where it is placed', () => {
  // typedShapes.test.ts owns the byte-identity of these two against MATLAB's JSON;
  // this is the XML side, which is where the mxchar envelope used to escape.
  it('a char field of a struct is Class="char" with a Dimension', () => {
    const xml = entry('../fixtures/typed_text.sldd', 'sCharMat', true).serializeXml('P', { Name: 'Value' }, 0);
    expect(xml).toContain('<P Name="m" Class="char" Dimension="2*3">abcdef</P>');
    // And the 1x3 row beside it still says nothing — one rule, both placements.
    expect(xml).toContain('<P Name="r" Class="char">row</P>');
  });

  it('a char element of a nested cell is Class="char" with a Dimension', () => {
    const xml = entry('../fixtures/typed_text.sldd', 'cTyped', true).serializeXml('P', { Name: 'Value' }, 0);
    expect(xml).toContain('<Element Class="char" Dimension="2*2">acbd</Element>');
  });
});

describe('charNeedsShape is the one rule all four channels apply', () => {
  it('is true for everything but a rank<=2 row', () => {
    expect(charNeedsShape([1, 4])).toBe(false);
    expect(charNeedsShape([1, 1])).toBe(false);
    expect(charNeedsShape([1, 0])).toBe(false);
    expect(charNeedsShape([3, 1])).toBe(true);
    expect(charNeedsShape([2, 2])).toBe(true);
    // Rank >= 3 always states its shape, even when the first extent is 1: a 1x3x2 is
    // not a row, and read as one it would come back with a page missing.
    expect(charNeedsShape([1, 3, 2])).toBe(true);
  });
});

describe('committing a char’s own displayed literal changes nothing', () => {
  // The fifth channel, and the one with no file to compare against: the table shows
  // ['ab'; 'cd'] and seeds the editor with that text, so a commit that edits nothing
  // must be a no-op. It was not — tokenizeStrings discarded WHICH quote was used, so
  // both spellings came back as a string array and the entry was silently retyped and
  // reshaped. MATLAB's answers for each spelling are in probe_char_shape.m's LITERALS
  // section; matlabValueParser.test.ts pins them at the parser.
  for (const [name, dims, display, text] of CASES) {
    if (dims.length > 2) {
      continue; // no literal to type back — the display is a summary
    }
    it(`${name}: retyping ${display} keeps char ${dims.join('x')}`, () => {
      const n = entry('../fixtures/char_text.sldd', name);
      const before = JSON.stringify(entry('../fixtures/char_text.sldd', name, true).serializeValue());
      expect(n.setProperty('Value', display)).toBe(true);
      expect([n._kind, n._scalarType, n._scalarValue]).toEqual(['scalar', 'char', text]);
      expect(n.dims).toEqual(dims);
      expect(n.displayValue).toBe(display);
      expect(JSON.stringify(n.serializeValue())).toBe(before);
    });
  }

  it('a char matrix is refused as an ELEMENT of a string array', () => {
    // One element of a string array holds one piece of text, and MATLAB errors on the
    // size for `s(1) = ['ab'; 'cd']`, so the element editor refuses it rather than
    // storing something the file cannot hold. `dims` is present on exactly the
    // multi-row chars, which is what makes it the test.
    const n = entry('../fixtures/char_text.sldd', 'charRow');
    expect(n.setProperty('Value', '["a" "b"]')).toBe(true);
    expect([n._kind, n.dims]).toEqual(['string', [1, 2]]);
    const el = n.children[0];
    expect(el.setProperty('Value', "['ab'; 'cd']")).toEqual({
      error: true,
      reason: 'String elements must be character or string values',
      invalidValue: "['ab'; 'cd']",
      validValue: '"a"',
    });
    // A single row is one piece of text and stays acceptable.
    expect(el.setProperty('Value', "['ab' 'cd']")).toBe(true);
    expect(el.displayValue).toBe('"abcd"');
  });
});
