// Copyright 2026 The MathWorks, Inc.
//
// Defects 22 and 24: a text dictionary's `_value` literal grammar cannot spell
// every value, and the writer acted as though it could.
//
// Two kinds of value have no literal form: rank >= 3 of any class (defect 22), and
// complex at ANY rank (defect 24). Both go out as a `{"_type": "cdata"}` uuencoded
// MAT byte stream, which is what MATLAB itself writes for them.
//
// The literal `Matrix(2,3,2)\n[[...]]` this used to emit is not merely unusual —
// MATLAB READS every candidate rank-3 spelling back as an empty 1x0 or the scalar
// 0 (test/parity/matlab/probe_rank3_serial.m), so every save of an N-D value
// destroyed it. What MATLAB itself writes for a rank >= 3 value, of EVERY class, is
// a `{"_type": "cdata"}` uuencoded MAT byte stream (probe_nd_rich.m), placed at the
// leaf wherever the value sits — entry value, object property, struct field, cell
// element, two levels down — with every container above it in its ordinary JSON
// form (probe_nd_nested.m).
//
// So the assertions here are against MATLAB's own bytes and MATLAB's own JSON:
//
//   * fixtures/nd_rich.sldd     — thirteen kinds at rank 3, one entry each. Our
//                                 writer must reproduce each cdata string exactly.
//   * fixtures/nd_nested.sldd   — the same value nested six ways. Our serialization
//                                 must equal MATLAB's whole value object.
//   * artifacts/text/cases.sldd — the three rank-3 entries, EDITED, because a form
//                                 that only round-trips untouched values is worth
//                                 nothing to a consumer that writes.
//
// Both fixtures were written by MATLAB and are read here as ground truth, never
// regenerated by us.
//
// MATLAB was also asked directly, which is the only acceptance criterion that
// matters: every entry below was spliced into MATLAB's own dictionary and reopened
// with Simulink.data.dictionary.open. Fifty-four cases — thirteen ND kinds, six
// placements, nine typed/char shapes, six char shapes, seven char retypes, two
// complex, three entry edits, three Parameter edits, five grammar literals — all read
// back isequal, same class, same size, with the edits in the right cell:
// `WRITEBACK FAILURES 0 of 54` (see probe_writeback.mjs / probe_writeback.m).
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { loadFile, findEntry } from './parity/loadFile.js';
import DataNode from '../src/datamodel/node/DataNode.js';
import NodeRegistry from '../src/datamodel/node/NodeRegistry.js';
import { isMatCdata } from '../src/datamodel/parser/CdataCodec.js';
import '../src/datamodel/node/NodeClassMap.js';

const truth = JSON.parse(
  readFileSync(fileURLToPath(new URL('./parity/artifacts/truth.json', import.meta.url)), 'utf8'),
);

/** The entries of a text dictionary exactly as MATLAB wrote them. */
function rawEntries(rel: string): { name: string; value: unknown }[] {
  const json = JSON.parse(readFileSync(fileURLToPath(new URL(rel, import.meta.url)), 'utf8'));
  return json.__MW_TEXT_PARTS__['__MW_TEXT_PART__/data/chunk0'].__MW_TEXT_content.entries;
}

/** The same entry through our reader, marked so the value goes through the WRITER. */
function modified(rel: string, filename: string, name: string): any {
  const n: any = findEntry(loadFile(rel, filename), name);
  expect(n, name + ' is not in ' + filename).toBeTruthy();
  // An untouched .sldd value replays _rawInput verbatim, which is a byte copy and
  // proves nothing about the writer. Every check here goes through the writer.
  n._markModified();
  return n;
}

const RICH = rawEntries('./fixtures/nd_rich.sldd');
const NESTED = rawEntries('./fixtures/nd_nested.sldd');

describe('a rank >= 3 value serializes to the cdata MATLAB wrote, byte for byte', () => {
  it('covers all thirteen kinds the fixture carries', () => {
    // A regenerated fixture that loses a kind must not quietly shrink the suite.
    expect(RICH.map((e) => e.name).sort()).toEqual([
      'ndCellMixed', 'ndChar', 'ndComplex', 'ndDouble', 'ndInt32', 'ndLogical', 'ndSingle',
      'ndStride3', 'ndStride4', 'ndStride5', 'ndStride6', 'ndStructMulti', 'ndUint64',
    ]);
  });

  for (const entry of RICH) {
    it(entry.name + ' rebuilds MATLAB’s own byte stream', () => {
      // The strongest form available: not "our reader reads it back", which is
      // self-consistency, but the same characters MATLAB put in the file. Reached
      // from the live node tree, so the shape, the class, the element order and
      // the field-name stride all have to be right at once.
      const n = modified('../fixtures/nd_rich.sldd', 'nd_rich.sldd', entry.name);
      expect(n.serializeValue()).toEqual(entry.value);
    });
  }

  it('a 2x3 double keeps the rank-2 literal — the cdata is not a blanket rule', () => {
    // The control. Rank 2 has a spelling MATLAB reads, and it is the spelling
    // MATLAB writes; switching those to cdata would be a different defect.
    const n = modified('./artifacts/text/cases.sldd', 'cases.sldd', 'mat2x3');
    expect(n.serializeValue()).toEqual({ _type: 'double', _value: 'Matrix(2,3)\n[[1.0, 2.0, 3.0]; [4.0, 5.0, 6.0]]' });
  });

  it('an N-D char keeps every extent on the way to the MAT stream', () => {
    // _buildVarObject spelled a char's shape as `[1, text.length]`, so MATLAB's own
    // reshape('abcdefghijkl', [2 3 2]) went back into a dictionary as a 1x12 row and
    // MATLAB then read it back as one: the characters survived, the shape did not.
    // The byte-equality above is what catches this now; this states the mechanism,
    // because a 1x12 stream is a perfectly valid stream and only its dims are wrong.
    const n = modified('../fixtures/nd_rich.sldd', 'nd_rich.sldd', 'ndChar');
    expect(n._var.dimensions).toEqual([2, 3, 2]);
    expect(n._var.className).toBe('char');
    expect(n._var.value).toBe('abcdefghijkl');
  });
});

describe('a complex value serializes to the cdata MATLAB wrote, at every rank', () => {
  // Defect 24. Rank was never the whole rule: MATLAB stores a complex SCALAR and a
  // complex VECTOR as byte streams too, and cases.sldd — written by MATLAB — proves
  // it in its own bytes, since cplxScalar and cplxVec are both `{"_type": "cdata"}`
  // with a `  %)` payload rather than any literal.
  //
  // What we emitted instead was `{"_type": "cdata", "_value": "3+4i"}` for the scalar
  // and, worse, a JSON LIST of those objects for the vector — a form MATLAB has never
  // been observed to write. The plain text is the BINARY dictionary's spelling for
  // the same property, and MATLAB reads it back out of a TEXT dictionary as an empty
  // 1x0 double: probe_writeback's complex/cplxScalar and complex/cplxVec both
  // reported `class=double size=[1 0] numel=0` before this fix and both now reopen
  // isequal to 3+4i and [1+2i 3-4i]. Same signature as defects 19 and 22 — data loss
  // on the first save, not diff churn.
  const CASES = rawEntries('./parity/artifacts/text/cases.sldd');

  for (const name of ['cplxScalar', 'cplxVec']) {
    it(name + ' rebuilds MATLAB’s own byte stream', () => {
      const truthValue = CASES.find((e) => e.name === name)?.value;
      // Guards the premise: if a regenerated corpus ever spells complex some other
      // way, this must fail loudly rather than compare our output to undefined.
      expect(isMatCdata(truthValue), name + ' is not a MAT byte stream in cases.sldd').toBe(true);
      const n = modified('./artifacts/text/cases.sldd', 'cases.sldd', name);
      expect(n.serializeValue()).toEqual(truthValue);
    });
  }

  it('the XML channel still writes the plain-text complex property from the stream', () => {
    // The stream is right for BOTH formats, which is why one serialization can serve
    // them: _serializeTypedPropertyXml discriminates on isMatCdata and hands a stream
    // back to the node, which writes the `IsComplex="1"` property a binary dictionary
    // wants. Emitting the stream to fix the text format therefore costs the XML
    // format nothing.
    const n = modified('./artifacts/text/cases.sldd', 'cases.sldd', 'cplxVec');
    expect(DataNode.serializePropertyXml('Value', n.serializeValue(), 0, null)).toBe(
      '<P Name="Value" Class="double" IsComplex="1" Dimension="1*2">1.0+2.0i 3.0-4.0i</P>',
    );
  });
});

describe('the cdata sits at the leaf, and the containers above it do not change', () => {
  // probe_nd_nested.m put the same 2x3x2 double in six positions and dumped what
  // MATLAB wrote. Each entry below is compared against that whole value object, so
  // a fix that put the cdata one level too high — the whole Simulink.Parameter, or
  // the whole scalar struct — fails here even though the value inside it survives.
  it('covers all six placements the fixture carries', () => {
    expect(NESTED.map((e) => e.name).sort()).toEqual([
      'ndInCell', 'ndInStruct', 'ndParam', 'ndSignal', 'ndTop', 'ndTwoLevel',
    ]);
  });

  for (const entry of NESTED) {
    it(entry.name + ' serializes to MATLAB’s own value object', () => {
      const n = modified('../fixtures/nd_nested.sldd', 'nd_nested.sldd', entry.name);
      // toEqual compares own properties, not key order — the one difference from
      // MATLAB's bytes is that a multi-field struct element spells its keys
      // alphabetically ("deep" before "flat") where we spell them in _fields order.
      // JSON object key order carries no meaning, and MATLAB confirmed it: the
      // spliced ndInStruct reopened isequal to its own (probe_writeback).
      expect(n.serializeValue()).toEqual(entry.value);
    });
  }

  it('a Simulink.Parameter converts its Value and nothing else', () => {
    const n = modified('../fixtures/nd_nested.sldd', 'nd_nested.sldd', 'ndParam');
    const props = (n.serializeValue() as any)._elements[0]._properties;
    expect(isMatCdata(props.Value)).toBe(true);
    // Dimensions is a 1x3 double — rank 2, so it keeps the plain list MATLAB
    // spells it with. A blanket "N-D goes to cdata" reading of the rule would have
    // converted the property that DESCRIBES the shape as well as the value.
    expect(props.Dimensions).toEqual([2, 3, 2]);
    expect(props.Complexity).toBe('real');
  });

  it('a struct converts the N-D field only', () => {
    const n = modified('../fixtures/nd_nested.sldd', 'nd_nested.sldd', 'ndInStruct');
    const out = n.serializeValue() as any;
    expect(out._array_type).toBe('Struct');
    expect(out._dimensions).toEqual([1, 1]);
    expect(out._fields).toEqual(['flat', 'deep']);
    expect(isMatCdata(out._elements[0].deep)).toBe(true);
    expect(out._elements[0].flat).toBe(7);
  });

  it('a cell converts the N-D element only', () => {
    const n = modified('../fixtures/nd_nested.sldd', 'nd_nested.sldd', 'ndInCell');
    const out = n.serializeValue() as any;
    expect(out._array_type).toBe('Cell');
    expect(out._dimensions).toEqual([1, 2]);
    expect(out._elements[0]).toBe(1);
    expect(isMatCdata(out._elements[1])).toBe(true);
  });
});

describe('the XML channel takes the same value through its own writer', () => {
  // serializeValue() is not only the text .sldd's form: DataNode.serializePropertyXml
  // and the cross-format paste path share it. A byte stream has no text XML form, so
  // the cdata arm reads it back into a node and lets that node write its own XML —
  // the same writer the .slx path uses for the value in the first place.
  it('an N-D cell reaches the XML writer as Dimension="2*2*2" with eight elements', () => {
    const n = modified('../fixtures/nd_rich.sldd', 'nd_rich.sldd', 'ndCellMixed');
    const xml = DataNode.serializePropertyXml('Value', n.serializeValue(), 0, null);
    expect(xml.split('\n')[0]).toBe('<P Name="Value" Class="cell" Dimension="2*2*2">');
    expect((xml.match(/^ {4}<Element /gm) ?? []).length).toBe(8);
  });

  it('an N-D struct array reaches it as Dimension="2*2*2" with each field’s own class', () => {
    const n = modified('../fixtures/nd_rich.sldd', 'nd_rich.sldd', 'ndStructMulti');
    const xml = DataNode.serializePropertyXml('Value', n.serializeValue(), 0, null);
    expect(xml.split('\n')[0]).toBe('<P Name="Value" Class="struct" Dimension="2*2*2">');
    // The fields are a double scalar, a char row and an int32 1x2 — three classes,
    // and each has to be named as itself. MATLAB's own binary dictionary writes a
    // struct's typed-array field as `Class="int32" Dimension="1*2">1 2`
    // (probe_typed_shapes.m), which is exactly the first element below. Before the
    // typed-vector fix the int32 field arrived here as a LIST of per-element typed
    // literals and was written `Class="double" Dimension="1*2">[object Object]
    // [object Object]` — a corrupt property carrying no numbers at all.
    expect(xml).toContain('\n        <P Name="a" Class="double">1.0</P>\n');
    expect(xml).toContain('\n        <P Name="bb" Class="char">e1</P>\n');
    expect(xml).toContain('\n        <P Name="cccccccc" Class="int32" Dimension="1*2">1 2</P>\n');
    // Eight elements, each with all three fields: the field-name table and the
    // element stride are both in the byte stream, and a wrong stride reads back as
    // eight elements of one field or two of three.
    expect((xml.match(/^ {4}<Element>/gm) ?? []).length).toBe(8);
    expect((xml.match(/^ {8}<P Name="cccccccc"/gm) ?? []).length).toBe(8);
  });

  it('an N-D complex value writes the complex XML form, not six-bit characters', () => {
    // The trap the `cdata` tag sets: it means two different things. In a BINARY
    // dictionary it is a plain-text complex property ({_value: '1+2i'}); in a TEXT
    // dictionary it is a MAT byte stream. Handing the stream to the complex writer
    // produces a file that opens and reads back as garbage, so isMatCdata
    // discriminates on the payload's first four characters.
    const n = modified('../fixtures/nd_rich.sldd', 'nd_rich.sldd', 'ndComplex');
    const xml = DataNode.serializePropertyXml('Value', n.serializeValue(), 0, null);
    expect(xml).toBe(
      '<P Name="Value" Class="double" IsComplex="1" Dimension="2*2*2">' +
        '1.0+11.0i 2.0+12.0i 3.0+13.0i 4.0+14.0i 5.0+15.0i 6.0+16.0i 7.0+17.0i 8.0+18.0i</P>',
    );
  });

  it('a binary dictionary’s plain-text complex property still writes as it did', () => {
    // The other meaning of the same tag, unchanged: BinarySlddParser hands the
    // property through as {_type: 'cdata', _value: '1+2i'}.
    expect(DataNode.serializePropertyXml('Value', { _type: 'cdata', _value: '1+2i' }, 0, null)).toBe(
      '<P Name="Value" Class="double" IsComplex="1">1.0+2.0i</P>',
    );
  });
});

describe('an edit to one element of an N-D value survives the round trip', () => {
  // The case a consumer actually produces: a user commits one cell. MATLAB confirmed
  // all three — (1,1,1) is 99 and the other eleven are untouched, at 2x3x2, in
  // MATLAB's own reopened dictionary.
  const REST = ['2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'];

  function edited(name: string, label: string, deep: boolean): any {
    const n: any = findEntry(loadFile('./artifacts/text/cases.sldd', 'cases.sldd'), name);
    const cell = n.children.find((c: any) => c.displayName === label);
    expect(cell, 'no child labelled ' + label).toBeTruthy();
    (deep ? cell.children[0] : cell).setProperty('Value', '99');
    const out = n.serializeValue() as any;
    expect(out._type).toBe('cdata');
    return NodeRegistry.parseValue(out, name, null);
  }

  it('a 2x3x2 double keeps eleven elements and the shape', () => {
    const back = edited('nd2x3x2', 'nd2x3x2(1,1,1)', false);
    expect(back._dims).toEqual([2, 3, 2]);
    // The tree lists a numeric array's children row-major, so element (1,1,1) is
    // child 0 here while MATLAB's linear order puts 4 second (defect 14). The
    // subscripts are what carry the meaning either way.
    expect(truth.vars.nd2x3x2.size).toEqual([2, 3, 2]);
    expect(back.children.map((c: any) => c.displayName)).toEqual([
      'nd2x3x2(1,1,1)', 'nd2x3x2(1,2,1)', 'nd2x3x2(1,3,1)', 'nd2x3x2(2,1,1)', 'nd2x3x2(2,2,1)', 'nd2x3x2(2,3,1)',
      'nd2x3x2(1,1,2)', 'nd2x3x2(1,2,2)', 'nd2x3x2(1,3,2)', 'nd2x3x2(2,1,2)', 'nd2x3x2(2,2,2)', 'nd2x3x2(2,3,2)',
    ]);
    expect(back.children.map((c: any) => c.displayValue)).toEqual(['99', ...REST]);
  });

  it('a 2x3x2 cell keeps eleven elements and the shape', () => {
    const back = edited('cellNd', 'cellNd{1,1,1}', false);
    expect(back._dims).toEqual([2, 3, 2]);
    expect(back.children[0].displayName).toBe('cellNd{1,1,1}');
    expect(back.children.map((c: any) => c.displayValue)).toEqual(['99', ...REST]);
  });

  it('a 2x3x2 struct array keeps eleven elements, its field and the shape', () => {
    const back = edited('structNd', 'structNd(1,1,1)', true);
    expect(back._dims).toEqual([2, 3, 2]);
    expect(back.displayValue).toBe('<2x3x2 struct>');
    expect(back.children[0].children[0].name).toBe('a');
    expect(back.children.map((c: any) => c.children[0].displayValue)).toEqual(['99', ...REST]);
  });
});
