// Copyright 2026 The MathWorks, Inc.
//
// Defect 21: a typed array's `_value` literal, at every shape and every placement.
//
// `test/fixtures/typed_text.sldd` was written by MATLAB — nine entries covering an
// int32 row, column and matrix, a single row, a logical row, a uint64 row, a struct of
// four typed fields, a struct holding a char matrix, and a cell of all four classes.
// It is read here as ground truth and never regenerated by us, so each assertion is
// against MATLAB's own characters rather than against our reader's opinion of them.
//
// What MATLAB's bytes say about the literal, six times over:
//
//   1xN  ->  [1, 2, 3]                    bare, no header
//   Nx1  ->  Matrix(3,1)\n[1, 2, 3]       header, flat body
//   MxN  ->  Matrix(2,2)\n[[1, 2]; [3, 4]]   header, one bracketed group per row
//
// The row is the interesting one: it carries no shape at all, because a bare list read
// back IS a row, while the column has to say so or it would come back transposed. Our
// writer put `Matrix(1,N)` on the row as well — recorded as defect 21 and left alone
// as cosmetic, on the reasoning that one spelling for every typed array beats matching
// MATLAB's two. That reasoning did not survive looking at our own code:
// BinarySlddParser.formatTypedVector has always written a row bare on the READ path,
// under the very same `dims.length <= 2 && dims[0] === 1` guard, so the codebase held
// both spellings already and the write path was the one disagreeing with MATLAB AND
// with its neighbour. The cost was a diff on every save of the commonest typed shape
// there is.
//
// MATLAB reads either form — probe_writeback's literal/i16Vec spliced
// `Matrix(1,3)\n[1, 2, 3]` into MATLAB's own dictionary and it reopened as
// int16([1 2 3]) — so this was churn, not loss. It is fixed because churn in a file
// people keep under source control is still a cost, and because byte-identity is the
// only parity claim that needs no argument.
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { loadFile, findEntry } from './parity/loadFile.js';
import '../src/datamodel/node/NodeClassMap.js';

const RAW: { name: string; value: unknown }[] = JSON.parse(
  readFileSync(fileURLToPath(new URL('./fixtures/typed_text.sldd', import.meta.url)), 'utf8'),
).__MW_TEXT_PARTS__['__MW_TEXT_PART__/data/chunk0'].__MW_TEXT_content.entries;

function truthOf(name: string): unknown {
  const hit = RAW.find((e) => e.name === name);
  expect(hit, name + ' is not in typed_text.sldd').toBeTruthy();
  return (hit as { value: unknown }).value;
}

/**
 * Mark this node AND every node under it modified, so the WRITER produces the value
 * instead of the reader replaying it.
 *
 * `_markModified` walks up the chain and never down, so marking a struct entry leaves
 * its fields unmodified — and an unmodified node replays its `_rawInput` verbatim. A
 * container checked without this is a byte copy of the fixture that would pass while
 * the writer was never asked anything, which is exactly how the gate itself was
 * issuing empty passes until probe_writeback grew the same helper.
 */
function deepMark(n: any): void {
  n._markModified();
  for (const c of n.children ?? []) {
    deepMark(c);
  }
}

function entry(name: string): any {
  const n = findEntry(loadFile('../fixtures/typed_text.sldd', 'typed_text.sldd'), name);
  deepMark(n);
  return n;
}

describe('a typed array serializes to the literal MATLAB wrote, at every shape', () => {
  it('covers all nine entries the fixture carries', () => {
    // A regenerated fixture that loses a shape must not quietly shrink the suite.
    expect(RAW.map((e) => e.name).sort()).toEqual([
      'cTyped', 'i32Col', 'i32Mat', 'i32Vec', 'lglVec', 'sCharMat', 'sTyped', 'sglVec', 'u64Vec2',
    ]);
  });

  // The four rows, one per class that cannot travel as bare JSON: a signed integer
  // (no suffix), a single ('F'), a logical (no suffix, and 1/0 rather than
  // true/false), an unsigned integer ('U'). Each is the shape that used to gain a
  // `Matrix(1,N)` header.
  for (const name of ['i32Vec', 'sglVec', 'lglVec', 'u64Vec2']) {
    it(name + ' is a bare list, byte for byte', () => {
      expect(entry(name).serializeValue()).toEqual(truthOf(name));
    });
  }

  it('i32Col keeps the header — a column has to state its shape', () => {
    // The control for the rule above. Written bare, this 3x1 would read back as a 1x3:
    // the orientation is the only thing the header carries here, and it is the whole
    // difference between the value MATLAB stored and its transpose.
    expect(entry('i32Col').serializeValue()).toEqual({ _type: 'int32', _value: 'Matrix(3,1)\n[1, 2, 3]' });
    expect(entry('i32Col').serializeValue()).toEqual(truthOf('i32Col'));
  });

  it('i32Mat keeps the header and one bracketed group per row', () => {
    // The other control: '; '-joined groups, never the newline-joined body MATLAB
    // reads back as an empty 1x0 (defect 19).
    expect(entry('i32Mat').serializeValue()).toEqual({ _type: 'int32', _value: 'Matrix(2,2)\n[[1, 2]; [3, 4]]' });
    expect(entry('i32Mat').serializeValue()).toEqual(truthOf('i32Mat'));
  });

  it('a typed field of a struct takes the same literal, whole', () => {
    // The placement that produced defect 23: mapping serializeValue over an array
    // field's CHILDREN yields a JSON list of per-element typed objects, and because
    // serializeValue is shared with the XML channel that list was String()-joined into
    // `Class="double" Dimension="1*2">[object Object] [object Object]` — a property
    // carrying no numbers at all. MATLAB spells the field as ONE literal for the whole
    // array, exactly as it spells a top-level entry.
    expect(entry('sTyped').serializeValue()).toEqual(truthOf('sTyped'));
  });

  it('a typed element of a nested cell takes the same literal too', () => {
    // Three levels: entry cell -> inner cell -> int32 vector, plus a single, a logical
    // and a char matrix beside it. The one divergence from MATLAB's bytes is a key we
    // add and MATLAB does not — see the test below — so this compares the value
    // through it.
    const elems = (entry('cTyped').serializeValue() as any)._elements[0]._elements;
    const truth = (truthOf('cTyped') as any)._elements[0]._elements;
    expect(elems).toEqual(truth);
  });

  it('records the one place we stamp _mw_element_type and MATLAB does not', () => {
    // Measured, not assumed: across cases.sldd, typed_text.sldd and nd_nested.sldd,
    // MATLAB writes `_mw_element_type: 'MATLABArray'` on the OUTERMOST wrapper of an
    // entry's value and on nothing below it — not on a nested cell (cellNest's two
    // inner levels), not on a nested struct (structNest.a, ndTwoLevel.inner), and not
    // on a wrapper held as an object PROPERTY (aBus's Elements_internal, aVariant's
    // fChoices). Five independent examples, no counter-example.
    //
    // We stamp every wrapper we write, so a nested one gains a key MATLAB omits.
    // MATLAB accepts it — probe_writeback's typed/cTyped reopens isequal to MATLAB's
    // own, same classes at every leaf — so this is diff churn of the same kind defect
    // 21 was, and it is recorded here rather than fixed because the key is written from
    // a dozen sites and none of them knows whether it is the outermost.
    const inner = (entry('cTyped').serializeValue() as any)._elements[0];
    expect(inner._mw_element_type).toBe('MATLABArray');
    expect((truthOf('cTyped') as any)._elements[0]._mw_element_type).toBeUndefined();
    // The outer wrapper agrees with MATLAB, which is the half that matters most: it is
    // the one a reader meets first.
    expect((entry('cTyped').serializeValue() as any)._mw_element_type).toBe('MATLABArray');
  });

  it('a struct holding a char matrix round-trips MATLAB’s mxchar untouched', () => {
    // Byte-identical, and — since defect 25 — from a node that UNDERSTANDS the body:
    // the field is a 2x3 char displaying `['ace'; 'bdf']`, and the literal is rebuilt
    // from its text rather than replayed. charShape.test.ts owns the rest of that rule;
    // this is the placement half, which is what this file is for.
    expect(entry('sCharMat').serializeValue()).toEqual(truthOf('sCharMat'));
  });
});

describe('a typed array displays and types itself as MATLAB does', () => {
  // The other half of the value: what the tree shows. Each element carries the array's
  // class rather than 'double', because the Data Type column reads it per row, and a
  // matrix's rows are named by subscript rather than by position (defect 8/11).
  const CASES: [string, string, string[], string[]][] = [
    ['i32Vec', '[1 2 3]', ['i32Vec(1)', 'i32Vec(2)', 'i32Vec(3)'], ['1', '2', '3']],
    ['i32Col', '[1; 2; 3]', ['i32Col(1)', 'i32Col(2)', 'i32Col(3)'], ['1', '2', '3']],
    ['i32Mat', '[1 2; 3 4]', ['i32Mat(1,1)', 'i32Mat(1,2)', 'i32Mat(2,1)', 'i32Mat(2,2)'], ['1', '2', '3', '4']],
    ['sglVec', '[1.5 2.5]', ['sglVec(1)', 'sglVec(2)'], ['1.5', '2.5']],
    // A logical shows true/false, not 1/0 — the literal's 1/0 is storage, not display.
    ['lglVec', '[true false true]', ['lglVec(1)', 'lglVec(2)', 'lglVec(3)'], ['true', 'false', 'true']],
    ['u64Vec2', '[1 2]', ['u64Vec2(1)', 'u64Vec2(2)'], ['1', '2']],
  ];

  for (const [name, display, subs, values] of CASES) {
    it(name + ' shows ' + display, () => {
      const n = findEntry(loadFile('../fixtures/typed_text.sldd', 'typed_text.sldd'), name);
      const cls = String(truthOf(name) ? (truthOf(name) as any)._type : '');
      expect([n.displayValue, n.dataType]).toEqual([display, cls]);
      expect(n.children.map((c: any) => c.displayName)).toEqual(subs);
      expect(n.children.map((c: any) => c.displayValue)).toEqual(values);
      expect(n.children.map((c: any) => c.dataType)).toEqual(subs.map(() => cls));
    });
  }

  it('a struct of typed fields keeps each field’s own class', () => {
    const n = findEntry(loadFile('../fixtures/typed_text.sldd', 'typed_text.sldd'), 'sTyped');
    expect([n.displayValue, n.dataType]).toEqual(['<1x1 struct>', 'struct']);
    expect(n.children.map((c: any) => [c.name, c.dataType, c.displayValue])).toEqual([
      ['a', 'int32', '[1 2]'],
      ['b', 'single', '3.5'],
      ['c', 'logical', 'true'],
      ['d', 'uint64', '[7 8]'],
    ]);
    // And the class reaches the elements of the array-valued fields, two levels down.
    expect(n.children[0].children.map((c: any) => c.dataType)).toEqual(['int32', 'int32']);
    expect(n.children[3].children.map((c: any) => c.dataType)).toEqual(['uint64', 'uint64']);
  });

  it('a cell of mixed classes types every element as itself', () => {
    const n = findEntry(loadFile('../fixtures/typed_text.sldd', 'typed_text.sldd'), 'cTyped');
    const inner = n.children[0];
    expect([n.dataType, inner.displayName, inner.dataType]).toEqual(['cell', 'cTyped{1}', 'cell']);
    expect(inner.children.map((c: any) => [c.displayName, c.dataType, c.displayValue])).toEqual([
      ['cTyped{1}{1}', 'int32', '[1 2]'],
      ['cTyped{1}{2}', 'single', '1.5'],
      ['cTyped{1}{3}', 'logical', 'true'],
      // A 2x2 char, read through MATLAB's mxchar literal: character codes, one
      // bracketed group per row. It used to come back as a numeric matrix of those
      // codes typed with the tag name itself — 'mxchar', which is not a MATLAB class
      // (defect 25).
      ['cTyped{1}{4}', 'char', "['ab'; 'cd']"],
    ]);
  });
});
