// Copyright 2026 The MathWorks, Inc.
//
// Regenerate the MATLAB corpus and report what changed. The corpus is checked in so the
// suite runs without MATLAB, which means it can silently go stale against a newer
// MATLAB. This is the command that catches that: run it when the MATLAB version changes,
// or before trusting a green parity run.
//
//   env DEX_MATLAB_CMD="mw -using Bmain matlab" npm run parity:drift
//
// Exits 0 when the regenerated truth matches what is committed, 1 when it does not,
// printing a per-variable diff. A non-zero exit is NOT necessarily a bug in our code — it
// may be a MATLAB behaviour change, which is exactly the thing worth knowing about.
//
// It compares truth.json, never container bytes. Only truth.json and meta.json are
// byte-reproducible; cases.mat, cases.slx and both cases.sldd differ on EVERY run,
// because MATLAB stamps each entry with a fresh uuid and lastmod. Comparing containers
// would report drift every single time and train the reader to ignore it.
import { execFileSync } from 'node:child_process';
import { readFileSync, existsSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = fileURLToPath(new URL('.', import.meta.url));
const ARTIFACTS = join(HERE, '..', 'artifacts');
const COMMITTED = join(ARTIFACTS, 'truth.json');
const LAUNCH = process.env.DEX_MATLAB_CMD || '';

if (!LAUNCH) {
  console.error('DEX_MATLAB_CMD is unset. Set it to the launcher plus its fixed args, e.g.');
  console.error('  env DEX_MATLAB_CMD="mw -using Bmain matlab" npm run parity:drift');
  process.exit(2);
}
if (!existsSync(COMMITTED)) {
  console.error('no committed truth at ' + COMMITTED + ' — run gen_truth.m first (Phase 2)');
  process.exit(2);
}

const out = mkdtempSync(join(tmpdir(), 'dexdrift-'));
const [bin, ...args] = LAUNCH.split(' ');
const script = join(HERE, 'gen_truth.m');
console.log('regenerating into ' + out);
// gen_truth.m honours an outdir set by the caller before run(...), so this never
// disturbs the committed copy — the regenerated corpus stays in the temp directory and
// is copied over by hand only if the new behaviour is judged correct.
execFileSync(
  bin,
  [...args, '-nodesktop', '-batch', `outdir='${out}'; run('${script}')`],
  { stdio: 'inherit', maxBuffer: 64 * 1024 * 1024 },
);

const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));
const fresh = readJson(join(out, 'truth.json'));
const old = readJson(COMMITTED);

// The MATLAB version is reported, NOT counted as drift: a version change is the usual
// REASON for running this, so counting it would put a guaranteed hit in front of the
// findings that matter. Print it so every diff below is read against the right release.
try {
  const vOld = readJson(join(ARTIFACTS, 'meta.json')).version;
  const vNew = readJson(join(out, 'meta.json')).version;
  console.log('\ncommitted corpus written by MATLAB ' + vOld);
  console.log('regenerated by                    ' + vNew);
} catch {
  // A missing or unreadable meta.json is not worth failing over — the value comparison
  // below is the actual check, and it does not depend on knowing the version.
  console.log('\n(could not read meta.json from one side; comparing values anyway)');
}

let drift = 0;
for (const section of ['vars', 'objArr']) {
  const a = old[section] || {};
  const b = fresh[section] || {};
  for (const name of new Set([...Object.keys(a), ...Object.keys(b)])) {
    const sa = JSON.stringify(a[name] ?? null);
    const sb = JSON.stringify(b[name] ?? null);
    if (sa !== sb) {
      drift++;
      console.log('\nDRIFT ' + section + '.' + name);
      console.log('  committed:   ' + sa);
      console.log('  regenerated: ' + sb);
    }
  }
}
// Both refusal maps. A change here is the MOST interesting kind of drift: it means
// MATLAB lifted (or added) a storage restriction, which retires — or adds — a skip.
for (const key of ['slddRejected', 'slxRejected']) {
  const ra = JSON.stringify(old.notes?.[key] ?? {});
  const rb = JSON.stringify(fresh.notes?.[key] ?? {});
  if (ra !== rb) {
    drift++;
    console.log('\nDRIFT notes.' + key);
    console.log('  committed:   ' + ra);
    console.log('  regenerated: ' + rb);
  }
}

if (drift === 0) {
  console.log('\nno drift: the committed corpus matches this MATLAB.');
  process.exit(0);
}
console.log('\n' + drift + ' variable(s) drifted. Review each, then re-copy the artifacts from');
console.log(out + ' if the new behaviour is correct —');
console.log('and update DESIGN.md if the CONVENTION changed, not just the value.');
process.exit(1);
